# -*- mode: ruby -*-
# vi: set ft=ruby :

# This vagrant box is built with Ubuntu 22.04 basebox from bento. Mini-NDN is
# pre-installed in this box. Recommended resource allocation for mini NDN:
# memory = "4096" cpus = "4". However, modifiy the memory, CPU cores, and other
# configuration as needed.

Vagrant.configure("2") do |config|
  config.vm.box = "netlab-memphis-minindn/minindn-0.7.0"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "4"
    vb.name = "mini-ndn-box"
  end
  config.vm.provider "vmware_desktop" do |vb|
    vb.memory = "4096"
    vb.cpus = "4"
  end
end
